spring.application.name=LogiStock_MS_02_Inventario
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/logiStock_MS_02
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

logging.file.name=${user.dir}/LogiStock_MS_02_Inventario/logs/MS_02_Inventario.log 

#${user.dir} para crear el archivo dentro de la carpeta del ms =).