CREATE DATABASE IF NOT EXISTS `logiStock_MS_01`;
CREATE DATABASE IF NOT EXISTS `logiStock_MS_02`;
CREATE DATABASE IF NOT EXISTS `logiStock_MS_03`;
CREATE DATABASE IF NOT EXISTS `logiStock_MS_04`;
CREATE DATABASE IF NOT EXISTS `logiStock_MS_05`;
CREATE DATABASE IF NOT EXISTS `logiStock_MS_06`;