server.port=8086
spring.application.name=LogiStock_MS_06_Ordenes_Despacho

spring.datasource.url=jdbc:mysql://localhost:3306/logiStock_MS_06
spring.datasource.username=root
spring.datasource.password=Fernandabravo.88

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.com.example.LogiStock_MS_06_Ordenes_Despacho=DEBUG
logging.level.org.hibernate.orm.results.mapping=TRACE

logging.file.name=logs/microservicio_despachos.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n