spring.application.name=LogiStock_MS_01_Productos

spring.datasource.url=jdbc:mysql://localhost:3306/logiStock_MS_01
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

logging.file.name=${user.dir}/LogiStock_MS_01_Productos/logs/MS_01_Productos.log 

#${user.dir} es una variable de Spring que apunta al directorio raíz del proyecto, 
#sin importar desde dónde ejecutes el comando. Así el archivo siempre se crea dentro de la carpeta del microservicio.