spring.application.name=LogiStock_MS_05_Ordenes_Compra

server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/logiStock
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

logging.file.name=${user.dir}/LogiStock_MS_05_Ordenes_Compra/logs/MS_05_Ordenes_Compra.log 

#${user.dir} apunta a la raiz del proyecto, logs se crean ahí ;).
