server.port=8086
spring.application.name=LogiStock_MS_06_Ordenes_Despacho

spring.datasource.url=jdbc:mysql://localhost:3306/logistock_despacho_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Fernandabravo.88

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false