server.port=8083
spring.application.name=LogiStock_MS_03_Proveedor

spring.datasource.url=jdbc:oracle:thin:@logistockdb_high?TNS_ADMIN=C:/Wallet
spring.datasource.username=ADMIN
spring.datasource.password=Fernandabravo.88

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true