server.port=8083
spring.application.name=LogiStock_MS_03_Proveedor

spring.datasource.url=jdbc:mysql://localhost:3306/logiStock_MS_03
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.defer-datasource-initialization=true

logging.file.name=logs/microservice-proveedor.log

spring.flyway.enabled=false