server.port=8084
spring.application.name=LogiStock_MS_04_Cliente

spring.datasource.url=jdbc:oracle:thin:@logistockdb_high?TNS_ADMIN=C:/Wallet
# Cambiamos ADMIN por el usuario del microservicio
spring.datasource.username=LogiStock_MS4
spring.datasource.password=Tu_Contraseña_De_LogiStock_MS4

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.default_schema=LOGISTOCK_MS4