spring.application.name=LogiStock_MS_01_Productos
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/logiStock_MS_01
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

logging.file.name=logs/MS_01_Productos.log 

